C:\Users\Simon Kalouche\Google Drive\3_Graduate_CMU\Research\Biorobotics\Projects\Puma\1_Mechanical\CAD\Puma\Leg\3-RSR Leg - V1\link2_foot-Static 1
C:\Users\Simon Kalouche\Google Drive\3_Graduate_CMU\Research\Biorobotics\Projects\Puma\1_Mechanical\CAD\Puma\Leg\3-RSR Leg - V1\link2_foot-Static 2
C:\Users\Simon Kalouche\Google Drive\3_Graduate_CMU\Research\Biorobotics\Projects\Puma\1_Mechanical\CAD\Puma\Leg\3-RSR Leg - V1\motor_to_hip_bracket-Static 2
C:\Users\Simon Kalouche\Google Drive\3_Graduate_CMU\Research\Biorobotics\Projects\Puma\1_Mechanical\CAD\Puma\Leg\3-RSR Leg - V1\motor_to_hip_bracket-Static 3
